bf16: true
cutoff_len: 2048
dataset: upper
dataset_dir: LLaMA-Factory/data
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 101
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: models/Qwen2_5-3b-Instruct
num_train_epochs: 10.0
optim: adamw_torch
output_dir: saves/Qwen2.5-3B-Instruct/lora/train_2025-05-14-18-46-48
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 5000
stage: sft
template: qwen
trust_remote_code: true
warmup_steps: 0
